name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        go: ["1.17"]
        os: [ubuntu-latest]
        # Test against latest stable release, v6 beta and v7 beta
        routeros: ["6.48.3", "6.49beta54"]
        legacy_bgp_support: [true]
        include:
          - experimental: false
            go: 1.17
            os: ubuntu-latest
            routeros: "6.49beta54"
            legacy_bgp_support: false
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Run provider tests
        run: make testacc
        env:
          MIKROTIK_HOST: 127.0.0.1:8728
          MIKROTIK_USER: admin
          MIKROTIK_PASSWORD: ''
          TF_ACC: 1
          LEGACY_BGP_SUPPORT: ${{ matrix.legacy_bgp_support }}

      - name: Run client tests
        run: make testclient
        env:
          MIKROTIK_HOST: 127.0.0.1:8728
          MIKROTIK_USER: admin
          MIKROTIK_PASSWORD: ''
          TF_ACC: 1
          LEGACY_BGP_SUPPORT: ${{ matrix.legacy_bgp_support }}

    services:
      routeros:
        image: evilfreelancer/docker-routeros:${{ matrix.routeros }}
        ports:
          - 8728:8728
        volumes:
          - /dev/net/tun:/dev/net/tun
        options: >-
          --cap-add=NET_ADMIN
